### PR TITLE
client-side/pre-push: Add a hint about the PR URL when pushing

### PR DESCRIPTION
**Pull request by tiramiseb**

### CODE REVIEW

**Comment by ifraixedes** [comment]
Sorry for my ignorance, but what does it actually do? showing the URL to the PR?

**Comment by xlr-8** [comment]
Could you add an example while running it please?

**Comment by tiramiseb** [comment]
```$ git push
############################
URL to create a pull request
https://github.com/cycloidio/cycloid-hooks/compare/hint_on_PR_url_when_push?expand=1
############################
Everything up-to-date```

Then, after pushing, we just have to click on the link to create a PR.

It's not foolproof, just a display to give a little help.

**Comment by xlr-8** [comment]
OK, I'm fine with the idea, I'd tend to make the output more discrete but that's really a matter of taste:

```bash
$ git push
To create a PR: https://github.com/cycloidio/cycloid-hooks/compare/hint_on_PR_url_when_push?expand=1

Everything up-to-date
```

So it's fine with me

**Comment by tiramiseb** [comment]
Well, when it is a new push then there are far more stuff on the screen and, in my opinion, the PR URL would likely be one of the most helpful things in there. That's why I intentionally made it visible. As you say, it's a matter of taste :)

```
$ git push --set-upstream origin hint_on_PR_url_when_push
fatal: argument 'origin/hint_on_PR_url_when_push..HEAD' ambigu : révision inconnue ou chemin inexistant.
Utilisez '--' pour séparer les chemins des révisions, comme ceci :
'git <commande> [<révision>...] -- [<chemin>...]'
############################
URL to create a pull request
https://github.com/cycloidio/cycloid-hooks/compare/hint_on_PR_url_when_push?expand=1
############################
Décompte des objets: 4, fait.
Delta compression using up to 4 threads.
Compression des objets: 100% (4/4), fait.
Écriture des objets: 100% (4/4), 552 bytes | 0 bytes/s, fait.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:cycloidio/cycloid-hooks.git
 * [new branch]      hint_on_PR_url_when_push -> hint_on_PR_url_when_push
La branche hint_on_PR_url_when_push est paramétrée pour suivre la branche distante hint_on_PR_url_when_push de origin en rebasant.
```

**Comment by ifraixedes** [comment]
I'm not mistaken, the URL will appear on each push; if that's the case, in my opinion, the URL is misguiding when the PR is already created; for example, quite a few times, I open a PR in WIP and work on the branch and push several times until the work is done, but the PR exists almost since the beginning.

If for you, that's OK; you can go ahead and merge it; it was worth to mention it, in case that you didn't contemplate such case.

**Comment by tiramiseb** [comment]
You are not mistaken, it will appear on all pushes. Personally, I don't mind. Like I said, it's not foolproof.
I spent maybe 5 minutes coding and testing this hint, I can imagine there are other not-foolproof side-effects. But we're not fool, so I guessed it is okay this way.
Moreover, you still can click on the link, you are redirected on a page to compare the commits with a link to the existing PR on the top right corner, so there is no risk to create two identical PRs.
I could spend time finding how to make it display only when there is no PR already (or change its label), but I don't think it's worth the time.

**Comment by ifraixedes** [comment]
If GH redirects to the open PR, then it isn't misguiding.
About @xlr-8 if you have any idea to change the message fro the first push and the rest, it will be good. First push as you did, following ones, one line output message will be better, but don't spend too much time on it if you don't know it.

A side of my above comment, I'm 👍 to merge it

**Comment by tiramiseb** [comment]
I'll merge, let's see how it goes. It can't hurt.

I took the habit to have the link after a push in GitLab, and I just missed it with GitHub. :)

**Pull request merged**
