### PR TITLE
Adding Gofmt and refreshing updating script 

### PR DESCRIPTION
**Pull request by xlr-8**
The gofmt hook has been added, it forces you to run go fmt before commiting, because it cannot modify the files for you before you commit. The update_script has also been updated because some hooks are now in a folder (pre-commit.d) and being called by the 'pre-commit' hook.

### CODE REVIEW

**Comment by Seraf** [comment]
Can you update the readme please ? Explaining how to install the hooks using your script etc :)

**Comment by xlr-8** [comment]
It's already done here: https://github.com/cycloidio/cycloid-hooks/tree/doc-update
Was waiting for the merge of this branch first as the reference are done from dev

**Comment by Seraf** [comment]
Great ! But for a workflow purpose, I think the doc related to the feature should come in the PR which bring this feature ;-)

**Comment by xlr-8** [comment]
It's not a doc link to this change but link to the overall README of the repository, which explains why it's not part of this one. If the README already existed, then I would have updated it, as it wasn't the case, I created another branch.

**Pull request merged**
